#!/usr/bin/env node
// Walk runtime dependencies and concatenate their LICENSE files into NOTICES.md.
// Run via `pnpm run notices` (also wired as a prebuild step in CI / docker build).

import { readFileSync, existsSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const root = resolve(__dirname, '..');

const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf-8'));
const deps = Object.keys(pkg.dependencies ?? {});

if (deps.length === 0) {
  console.log('[notices] no runtime deps, skipping.');
  process.exit(0);
}

const sections = [];

sections.push(`# Third-Party Notices

This file lists the runtime dependencies of \`${pkg.name}\` v${pkg.version} that
are bundled into the production build (\`dist/\`) and the Docker image, along
with their original copyright notices and license texts.

Generated by \`scripts/generate-notices.mjs\` — re-run with \`pnpm run notices\`
after adding or upgrading any runtime dependency.
`);

for (const name of deps.sort()) {
  const depPath = join(root, 'node_modules', name);
  if (!existsSync(depPath)) {
    console.warn(`[notices] skipping ${name}: not installed`);
    continue;
  }

  const depPkg = JSON.parse(readFileSync(join(depPath, 'package.json'), 'utf-8'));

  // Find the LICENSE file (case-insensitive, several common variants).
  const candidates = readdirSync(depPath).filter((f) => /^LICEN[CS]E(\.[A-Za-z0-9]+)?$/i.test(f));
  const licenseFile = candidates.length > 0 ? candidates[0] : null;
  const licenseBody = licenseFile
    ? readFileSync(join(depPath, licenseFile), 'utf-8').trim()
    : `(No LICENSE file shipped in this package. Declared license: ${depPkg.license ?? 'unknown'})`;

  const homepage =
    depPkg.homepage ??
    (typeof depPkg.repository === 'string' ? depPkg.repository : (depPkg.repository?.url ?? null));

  sections.push(`---

## ${name} v${depPkg.version}

- License: \`${depPkg.license ?? 'unknown'}\`
${homepage ? `- Homepage: ${homepage.replace(/^git\+|\.git$/g, '')}` : ''}

\`\`\`
${licenseBody}
\`\`\`
`);
  console.log(`[notices] included ${name} v${depPkg.version} (${depPkg.license ?? 'unknown'})`);
}

writeFileSync(join(root, 'NOTICES.md'), sections.join('\n'));
console.log(`[notices] wrote NOTICES.md (${deps.length} deps)`);
